name: Pull Requests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - railway

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - run: npm i
      - run: rm -rf node_packages
      - run: pnpm install --frozen-lockfile
      #- run: pnpm test
  qodana:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@v2024.3
        with:
          upload-result: true
          pr-mode: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    needs: test
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}



